[project]
name = "uup-builder"
version = "0.1.0"
description = "Python Module for building an iso from uup dump files."
requires-python = ">=3.10"
dependencies = [
    "uup-dump-api-py>=0.1.5",
]

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
